# Generated by Django 3.0.6 on 2020-06-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200602_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='note',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='prompt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
