# Generated by Django 3.0.6 on 2020-06-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20200602_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='contact',
            new_name='Deck',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='prompt',
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='flashcards.Flashcard')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='flashcards.Prompt')),
            ],
        ),
    ]
