# Generated by Django 3.0.6 on 2020-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_deck_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='star',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
